{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolords",
    "module": "ftclibrary",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ftclibrary-3.0.aar",
          "url": "ftclibrary-3.0.aar",
          "size": 151154,
          "sha512": "9ed459c4dcd1028901f54078c29cb8978767de9158b30ccb0b05a4c66df80f61338f00559ab85d9d8c980972821cb215c7ebf565d19f5f5ce4b92731f4de568c",
          "sha256": "2520d81cfc920db82be4f0a38f4b139a18405f2a8ddac99cfc9a7ecb4aecff6f",
          "sha1": "972cb142e8e801842383a1f10ef6062bb642462d",
          "md5": "2a7b4ef8f339d5822652a8b2e40e8069"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ftclibrary-3.0.aar",
          "url": "ftclibrary-3.0.aar",
          "size": 151154,
          "sha512": "9ed459c4dcd1028901f54078c29cb8978767de9158b30ccb0b05a4c66df80f61338f00559ab85d9d8c980972821cb215c7ebf565d19f5f5ce4b92731f4de568c",
          "sha256": "2520d81cfc920db82be4f0a38f4b139a18405f2a8ddac99cfc9a7ecb4aecff6f",
          "sha1": "972cb142e8e801842383a1f10ef6062bb642462d",
          "md5": "2a7b4ef8f339d5822652a8b2e40e8069"
        }
      ]
    }
  ]
}
