{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolords",
    "module": "ftclibrary",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftclibrary-2.2.aar",
          "url": "ftclibrary-2.2.aar",
          "size": 165866,
          "sha512": "6d32ddf922323b0d19d7d50b3ccfb577cc4a96697a3f030532bb001b48b2dcbd51b4ac014e58e5c2aa61d613919d7e47c40536f6c9c0991fdb4483fcac0b4cc6",
          "sha256": "b8775a41b9238f62c81b77939ac07f3ac23fe28e870914906aba148255678a58",
          "sha1": "ead61ec232839d6fab0151b2aba1489f8ab32e65",
          "md5": "6d25e9e79e58539880698bac24f733ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftclibrary-2.2.aar",
          "url": "ftclibrary-2.2.aar",
          "size": 165866,
          "sha512": "6d32ddf922323b0d19d7d50b3ccfb577cc4a96697a3f030532bb001b48b2dcbd51b4ac014e58e5c2aa61d613919d7e47c40536f6c9c0991fdb4483fcac0b4cc6",
          "sha256": "b8775a41b9238f62c81b77939ac07f3ac23fe28e870914906aba148255678a58",
          "sha1": "ead61ec232839d6fab0151b2aba1489f8ab32e65",
          "md5": "6d25e9e79e58539880698bac24f733ca"
        }
      ]
    }
  ]
}
